name: ML Churn Prototype
description: Prototype to demonstrate building a churn model on CML
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2020-09-29"
api_version: 1

tasks:
  - type: create_job
    name: Train Model
    entity_label: train_model
    script: code/train_model.py
    arguments: None
    short_summary: Job to train models
    kernel: python3

  - type: create_job
    name: Check Model
    entity_label: check_model
    script: code/model_check.py
    arguments: None
    short_summary: Job to train models
    kernel: python3

  - type: create_model
    name: Churn Model API Endpoint
    entity_label: telco_churn_model
    description: This model API endpoint is used to predict churn
    short_summary: Create the churn model prediction api endpoint
    default_resources:
      cpu: 1
      memory: 2
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Build Telco Churn Model Endpoint
    entity_label: telco_churn_model
    comment: Build churn model
    examples:
      - request: {
                    "StreamingTV": "No",
                    "MonthlyCharges": 70.35,
                    "PhoneService": "No",
                    "PaperlessBilling": "No",
                    "Partner": "No",
                    "OnlineBackup": "No",
                    "gender": "Female",
                    "Contract": "Month-to-month",
                    "TotalCharges": 1397.475,
                    "StreamingMovies": "No",
                    "DeviceProtection": "No",
                    "PaymentMethod": "Bank transfer (automatic)",
                    "tenure": 29,
                    "Dependents": "No",
                    "OnlineSecurity": "No",
                    "MultipleLines": "No",
                    "InternetService": "DSL",
                    "SeniorCitizen": "No",
                    "TechSupport": "No",
                }
        response: ""
    target_file_path: code/serve_explained_model.py
    target_function_name: explain
    kernel: python3

  - type: deploy_model
    name: telco_churn_model
    entity_label: telco_churn_model
    cpu: 1
    gpu: 0

  - type: start_application
    name: Application to Serve Churn UI
    subdomain: copmlchurnapp
    script: code/application.py
    kernel: python3
    memory: 1
    cpu: 1
    gpu: 0